#cloud-config
write_files:
-   content: |
      #!/bin/sh
      mkdir /mnt/webdata
      if test -b "/dev/sdb1";
      then
        mount -t ext3 /dev/sdb1 /mnt/webdata
      else
        parted -s /dev/sdb mklabel gpt mkpart primary '0%' '100%'
        mkfs -t ext3 -L WebVolume /dev/sdb1
        mount -t ext3 /dev/sdb1 /mnt/webdata
      fi
      chown opc:opc /mnt/webdata
    path: /home/opc/parted.mkfs.mount.sh
runcmd:
 -  [ chmod, "u+x", "/home/opc/parted.mkfs.mount.sh" ]
 -  [ source, "/home/opc/parted.mkfs.mount.sh" ]
 -  'echo "LABEL=WebVolume   /mnt/webdata   ext3   defaults,noatime,_netdev   0   2" | tee -a "/etc/fstab"'
