#cloud-config
runcmd:
 - [ "apt-get", "update" ]
 - [ "apt-get", "install", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common", "tree", "jq", "-y" ]
 - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
 - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
 - [ "apt-get", "update" ]
 - [ "apt-get", "install", "docker-ce", "docker-ce-cli", "containerd.io", "-y" ]
 - [ "usermod", "-aG", "docker", "ubuntu" ]
 - [ "mkdir", "/home/ubuntu/functions" ]
 - [ "wget", "-O", "/home/ubuntu/functions/blankfn.py", "https://raw.githubusercontent.com/mtjakobczyk/oci-book/master/chapter09/2-fn/blankfn.py?token=ABRSVT5N7B6JOL6ID5PHMKK5QYPNS" ]
 - [ "wget", "-O", "/home/ubuntu/functions/uuidfn.py", "https://raw.githubusercontent.com/mtjakobczyk/oci-book/master/chapter09/2-fn/uuidfn.py?token=ABRSVT2LAHFFX3H5WFCUEA25QZB3Q" ]
 - [ "wget", "-O", "/home/ubuntu/functions/reportingfn.py", "https://raw.githubusercontent.com/mtjakobczyk/oci-book/master/chapter09/2-fn/reportingfn.py?token=ABRSVTZHYOLYV2JQ2HOZAE25SIGTQ" ]
 - [ "wget", "-O", "/home/ubuntu/event.mock.json", "https://raw.githubusercontent.com/mtjakobczyk/oci-book/master/chapter09/4-events/events/event.mock.json?token=ABRSVT4UTLXPYQIH4TZZFGK5SIJGS" ]
final_message: "DEV machine is running, after $UPTIME seconds"
